---
- name: Create or Update application
  become: yes
  become_user: '{{ common_user }}'
  become_method: enable
  ansible.builtin.git:
    repo: '{{ item.repo }}'
    dest: '{{ item.location }}'
    version: '{{ item.version }}'
    force: '{{ item.force }}'
    accept_hostkey: yes
  with_items: '{{ common_deployments | default([]) }}'
  when:
    - common_deployments is defined
    - common_user != 'vagrant'
  tags:
    - apps
    - deploy
    - update
