---
- name: Create a directory if it does not exist
  become: yes
  become_user: '{{ common_user }}'
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: directory
    mode: '{{ item.mode }}'
  with_items: '{{ common_create_directories | default({}) }}'
  when:
    - common_create_directories

- name: Create files
  become: yes
  become_user: '{{ common_user }}'
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: touch
    owner: '{{ item.owner }}'
    mode: '{{ item.mode }}'
  with_items: '{{ common_create_files | default({}) }}'
  when:
    - common_create_files is defined
