---
- name: Install common package dependencies
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present
  become: true
  register: install_common_packages
  when: common_packages is defined
  tags:
    - install
