---
- name: Install common package dependencies
  become: true
  package: name={{ item }} state=present
  with_items: '{{ _common_packages | default([]) }}'
  register: install_common_packages
  when: _common_packages is defined
  tags:
    - install
    - apt
    - update_cache
