---
- name: Copy files local to remote
  become: true
  become_user: '{{ common_user }}'
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.path }}'
    mode: '{{ item.permissions }}'
    directory_mode: 0750
  with_items: '{{ common_copy_files | default({}) }}'
  tags:
    - copy_files

- name: create files before make directories
  block:
    - name: Create a directory if it does not exist
      become: yes
      become_user: '{{ common_user }}'
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: directory
        owner: '{{ item.owner }}'
        mode: '{{ item.mode }}'
      with_items: '{{ common_create_directories | default({}) }}'
      when:
        - common_create_directories

    - name: Create files
      become: yes
      become_user: '{{ common_user }}'
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: touch
        owner: '{{ item.owner }}'
        mode: '{{ item.mode }}'
      with_items: '{{ common_create_files | default({}) }}'
      when:
        - common_create_files is defined
